# Generated by Django 3.0.7 on 2020-06-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
    ]
