# Generated by Django 3.0.7 on 2020-06-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='long_text',
            field=models.TextField(default=''),
        ),
    ]
