# Generated by Django 3.0.7 on 2020-06-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200626_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=100)),
                ('first_caption', models.TextField(max_length=10000)),
                ('second_caption', models.TextField(max_length=10000)),
                ('second_title', models.CharField(max_length=100)),
                ('li_1', models.CharField(max_length=100)),
                ('li_2', models.CharField(max_length=100)),
                ('li_3', models.CharField(max_length=100)),
                ('li_4', models.CharField(max_length=100)),
                ('li_5', models.CharField(max_length=100)),
            ],
        ),
    ]
