# Generated by Django 3.0.7 on 2020-06-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200627_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='li_1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about_me',
            name='li_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about_me',
            name='li_3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about_me',
            name='li_4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='about_me',
            name='li_5',
            field=models.CharField(default='', max_length=100),
        ),
    ]
